export interface DeckCardItem {
  cardId: string;
  name: string;
  quantity: number;
  cost?: number | null;
  power?: number | null;
  category: string;
  colors: string;
  imageUrl?: string | null;
  yuyuPrice?: number | null;
  marketPrice?: number | null;
}

export interface RecommendedDeck {
  id: string;
  name: string;
  subname: string;
  leaderId: string;
  leaderName: string;
  leaderImage: string;
  color: string;
  colorDot: string;
  rank: string;
  winrate: string;
  date: string;
  tournament: string;
  source: string;
  metaEra?: string;
  tier?: string;
  description: string;
  cards: DeckCardItem[];
  stats: {
    charactersCount: number;
    eventsCount: number;
    stagesCount: number;
    counters2000: number;
    counters1000: number;
    noCounter: number;
    avgCost: number;
  };
}

export const RECOMMENDED_DECKS: RecommendedDeck[] = [
  {
    "id": "blue-donquixote-doflamingo-op01",
    "name": "(Blue) Donquixote Doflamingo",
    "subname": "Seven Warlords of the Sea",
    "leaderId": "OP01-060",
    "leaderName": "Donquixote Doflamingo",
    "leaderImage": "https://card.yuyu-tei.jp/opc/front/st17/10006.jpg",
    "color": "Blue",
    "colorDot": "#3b82f6",
    "rank": "#1 Tier 1",
    "winrate": "64.2%",
    "date": "20/09/2026",
    "tournament": "Tokyo Championship 2026 Regional Finals (1st Place)",
    "source": "OnePieceTopDecks",
    "metaEra": "OP-09",
    "tier": "Tier 1",
    "description": "Supreme Tier 1 meta powerhouse. Cycles the deck with Jinbe, Boa Hancock, and Kaya while locking the opponent board with Mihawk and Gravity Blade.",
    "cards": [
      {
        "cardId": "OP01-073",
        "name": "Donquixote Doflamingo",
        "quantity": 4,
        "cost": 3,
        "power": 4000,
        "category": "Character",
        "colors": "Blue",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/st17/10007.jpg",
        "yuyuPrice": 50,
        "marketPrice": 0.36
      },
      {
        "cardId": "OP01-070",
        "name": "Dracule Mihawk",
        "quantity": 2,
        "cost": 9,
        "power": 9000,
        "category": "Character",
        "colors": "Blue",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op01/10089.jpg",
        "yuyuPrice": 120,
        "marketPrice": 0.86
      },
      {
        "cardId": "OP01-078",
        "name": "Boa Hancock",
        "quantity": 4,
        "cost": 4,
        "power": 5000,
        "category": "Character",
        "colors": "Blue",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op01/10100.jpg",
        "yuyuPrice": 120,
        "marketPrice": 0.86
      },
      {
        "cardId": "OP07-040",
        "name": "Crocodile",
        "quantity": 4,
        "cost": 4,
        "power": 5000,
        "category": "Character",
        "colors": "Blue",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/prb02/10070.jpg",
        "yuyuPrice": 80,
        "marketPrice": 0.57
      },
      {
        "cardId": "OP07-046",
        "name": "Sengoku",
        "quantity": 4,
        "cost": 1,
        "power": 2000,
        "category": "Character",
        "colors": "Blue",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op07/10055.jpg",
        "yuyuPrice": 120,
        "marketPrice": 0.86
      },
      {
        "cardId": "OP01-077",
        "name": "Perona",
        "quantity": 4,
        "cost": 1,
        "power": 2000,
        "category": "Character",
        "colors": "Blue",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op01/10098.jpg",
        "yuyuPrice": 80,
        "marketPrice": 0.57
      },
      {
        "cardId": "OP02-054",
        "name": "Gecko Moria",
        "quantity": 4,
        "cost": 4,
        "power": 6000,
        "category": "Character",
        "colors": "Blue",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op02/10070.jpg",
        "yuyuPrice": 80,
        "marketPrice": 0.57
      },
      {
        "cardId": "ST03-008",
        "name": "Trafalgar Law",
        "quantity": 4,
        "cost": 1,
        "power": 1000,
        "category": "Character",
        "colors": "Blue",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/prb01/10187.jpg",
        "yuyuPrice": 50,
        "marketPrice": 0.36
      },
      {
        "cardId": "OP03-044",
        "name": "Kaya",
        "quantity": 4,
        "cost": 1,
        "power": null,
        "category": "Character",
        "colors": "Blue",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op03/10053.jpg",
        "yuyuPrice": 220,
        "marketPrice": 1.57
      },
      {
        "cardId": "OP01-071",
        "name": "Jinbe",
        "quantity": 4,
        "cost": 4,
        "power": 2000,
        "category": "Character",
        "colors": "Blue",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op01/10091.jpg",
        "yuyuPrice": 80,
        "marketPrice": 0.57
      },
      {
        "cardId": "OP06-058",
        "name": "Gravity Blade Raging Tiger",
        "quantity": 4,
        "cost": 7,
        "power": null,
        "category": "Event",
        "colors": "Blue",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op06/10070.jpg",
        "yuyuPrice": 220,
        "marketPrice": 1.57
      },
      {
        "cardId": "OP04-056",
        "name": "Gum-Gum Red Roc",
        "quantity": 4,
        "cost": 6,
        "power": null,
        "category": "Event",
        "colors": "Blue",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/prb01/10086.jpg",
        "yuyuPrice": 120,
        "marketPrice": 0.86
      },
      {
        "cardId": "OP01-086",
        "name": "Overheat",
        "quantity": 4,
        "cost": 2,
        "power": null,
        "category": "Event",
        "colors": "Blue",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/st17/10008.jpg",
        "yuyuPrice": 50,
        "marketPrice": 0.36
      }
    ],
    "stats": {
      "charactersCount": 38,
      "eventsCount": 12,
      "stagesCount": 0,
      "counters2000": 8,
      "counters1000": 20,
      "noCounter": 22,
      "avgCost": 3.4
    }
  },
  {
    "id": "black-rob-lucci-op07",
    "name": "(Black) Rob Lucci",
    "subname": "CP0 Government Intelligence",
    "leaderId": "OP07-079",
    "leaderName": "Rob Lucci",
    "leaderImage": "https://card.yuyu-tei.jp/opc/front/op07/10096.jpg",
    "color": "Black",
    "colorDot": "#475569",
    "rank": "#1 Tier 1",
    "winrate": "63.8%",
    "date": "18/09/2026",
    "tournament": "OnePieceTopDecks Flagship Battle 1st Place",
    "source": "OnePieceTopDecks",
    "metaEra": "OP-08",
    "tier": "Tier 1",
    "description": "Unrivaled board suppression and cost-reduction control. Loops 8-cost Gecko Moria, Rebecca, and Spandine to wipe opponent characters each turn.",
    "cards": [
      {
        "cardId": "OP06-086",
        "name": "Gecko Moria",
        "quantity": 4,
        "cost": 8,
        "power": 9000,
        "category": "Character",
        "colors": "Black",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op06/10103.jpg",
        "yuyuPrice": 120,
        "marketPrice": 0.86
      },
      {
        "cardId": "OP07-085",
        "name": "Stussy",
        "quantity": 4,
        "cost": 9,
        "power": 9000,
        "category": "Character",
        "colors": "Black",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op07/10103.jpg",
        "yuyuPrice": 220,
        "marketPrice": 1.57
      },
      {
        "cardId": "OP07-090",
        "name": "Morgans",
        "quantity": 4,
        "cost": 2,
        "power": 2000,
        "category": "Character",
        "colors": "Black",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op07/10109.jpg",
        "yuyuPrice": 30,
        "marketPrice": 0.21
      },
      {
        "cardId": "OP05-091",
        "name": "Rebecca",
        "quantity": 4,
        "cost": 4,
        "power": null,
        "category": "Character",
        "colors": "Black",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op05/10110.jpg",
        "yuyuPrice": 180,
        "marketPrice": 1.29
      },
      {
        "cardId": "OP03-089",
        "name": "Brannew",
        "quantity": 4,
        "cost": 2,
        "power": 3000,
        "category": "Character",
        "colors": "Black",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/st19/10008.jpg",
        "yuyuPrice": 50,
        "marketPrice": 0.36
      },
      {
        "cardId": "OP06-092",
        "name": "Brook",
        "quantity": 4,
        "cost": 6,
        "power": 6000,
        "category": "Character",
        "colors": "Black",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op06/10110.jpg",
        "yuyuPrice": 80,
        "marketPrice": 0.57
      },
      {
        "cardId": "OP02-099",
        "name": "Sakazuki",
        "quantity": 4,
        "cost": 6,
        "power": 7000,
        "category": "Character",
        "colors": "Black",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op02/10125.jpg",
        "yuyuPrice": 80,
        "marketPrice": 0.57
      },
      {
        "cardId": "OP03-086",
        "name": "Spandam",
        "quantity": 4,
        "cost": 1,
        "power": 2000,
        "category": "Character",
        "colors": "Black",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op03/10103.jpg",
        "yuyuPrice": 120,
        "marketPrice": 0.86
      },
      {
        "cardId": "OP03-080",
        "name": "Kaku",
        "quantity": 4,
        "cost": 5,
        "power": 6000,
        "category": "Character",
        "colors": "Black",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op03/10095.jpg",
        "yuyuPrice": 120,
        "marketPrice": 0.86
      },
      {
        "cardId": "OP02-096",
        "name": "Kuzan",
        "quantity": 4,
        "cost": 4,
        "power": 5000,
        "category": "Character",
        "colors": "Black",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op02/10121.jpg",
        "yuyuPrice": 120,
        "marketPrice": 0.86
      },
      {
        "cardId": "OP02-121",
        "name": "Kuzan",
        "quantity": 2,
        "cost": 10,
        "power": 10000,
        "category": "Character",
        "colors": "Black",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/prb01/10044.jpg",
        "yuyuPrice": 220,
        "marketPrice": 1.57
      },
      {
        "cardId": "OP06-096",
        "name": "...Nothing...at All!!!",
        "quantity": 4,
        "cost": 3,
        "power": null,
        "category": "Event",
        "colors": "Black",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op06/10115.jpg",
        "yuyuPrice": 30,
        "marketPrice": 0.21
      },
      {
        "cardId": "OP02-117",
        "name": "Ice Age",
        "quantity": 4,
        "cost": 1,
        "power": null,
        "category": "Event",
        "colors": "Black",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op02/10148.jpg",
        "yuyuPrice": 80,
        "marketPrice": 0.57
      }
    ],
    "stats": {
      "charactersCount": 42,
      "eventsCount": 8,
      "stagesCount": 0,
      "counters2000": 0,
      "counters1000": 20,
      "noCounter": 30,
      "avgCost": 4.5
    }
  },
  {
    "id": "black-marshall-d-teach-op09",
    "name": "(Black) Marshall.D.Teach",
    "subname": "Blackbeard Pirates",
    "leaderId": "OP09-081",
    "leaderName": "Marshall.D.Teach",
    "leaderImage": "https://card.yuyu-tei.jp/opc/front/op09/10101.jpg",
    "color": "Black",
    "colorDot": "#18181b",
    "rank": "#1 Tier 1",
    "winrate": "65.0%",
    "date": "22/09/2026",
    "tournament": "Yokohama Masters Grand Finals Champion",
    "source": "OnePieceTopDecks",
    "metaEra": "OP-09",
    "tier": "Tier 1",
    "description": "Oppressive leader nullification that shuts down On Play and When Attacking triggers across the field, backed by massive Blackbeard Pirates beatdown.",
    "cards": [
      {
        "cardId": "OP09-093",
        "name": "Marshall.D.Teach",
        "quantity": 4,
        "cost": 10,
        "power": 12000,
        "category": "Character",
        "colors": "Black",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op09/10114.jpg",
        "yuyuPrice": 120,
        "marketPrice": 0.86
      },
      {
        "cardId": "OP09-086",
        "name": "Jesus Burgess",
        "quantity": 4,
        "cost": 4,
        "power": 5000,
        "category": "Character",
        "colors": "Black",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/st27/10008.jpg",
        "yuyuPrice": 50,
        "marketPrice": 0.36
      },
      {
        "cardId": "OP09-082",
        "name": "Avalo Pizarro",
        "quantity": 4,
        "cost": 4,
        "power": 6000,
        "category": "Character",
        "colors": "Black",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op09/10103.jpg",
        "yuyuPrice": 30,
        "marketPrice": 0.21
      },
      {
        "cardId": "OP09-088",
        "name": "Shiryu",
        "quantity": 4,
        "cost": 3,
        "power": 4000,
        "category": "Character",
        "colors": "Black",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op09/10109.jpg",
        "yuyuPrice": 80,
        "marketPrice": 0.57
      },
      {
        "cardId": "OP09-089",
        "name": "Stronger",
        "quantity": 4,
        "cost": 1,
        "power": null,
        "category": "Character",
        "colors": "Black",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op09/10110.jpg",
        "yuyuPrice": 80,
        "marketPrice": 0.57
      },
      {
        "cardId": "OP09-092",
        "name": "Marshall.D.Teach",
        "quantity": 4,
        "cost": 3,
        "power": 4000,
        "category": "Character",
        "colors": "Black",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op09/10113.jpg",
        "yuyuPrice": 30,
        "marketPrice": 0.21
      },
      {
        "cardId": "OP02-096",
        "name": "Kuzan",
        "quantity": 4,
        "cost": 4,
        "power": 5000,
        "category": "Character",
        "colors": "Black",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op02/10121.jpg",
        "yuyuPrice": 120,
        "marketPrice": 0.86
      },
      {
        "cardId": "OP06-086",
        "name": "Gecko Moria",
        "quantity": 4,
        "cost": 8,
        "power": 9000,
        "category": "Character",
        "colors": "Black",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op06/10103.jpg",
        "yuyuPrice": 120,
        "marketPrice": 0.86
      },
      {
        "cardId": "OP05-091",
        "name": "Rebecca",
        "quantity": 4,
        "cost": 4,
        "power": null,
        "category": "Character",
        "colors": "Black",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op05/10110.jpg",
        "yuyuPrice": 180,
        "marketPrice": 1.29
      },
      {
        "cardId": "OP09-097",
        "name": "Black Vortex",
        "quantity": 4,
        "cost": 2,
        "power": null,
        "category": "Event",
        "colors": "Black",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op09/10120.jpg",
        "yuyuPrice": 30,
        "marketPrice": 0.21
      },
      {
        "cardId": "OP09-098",
        "name": "Black Hole",
        "quantity": 4,
        "cost": 4,
        "power": null,
        "category": "Event",
        "colors": "Black",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/prb02/10093.jpg",
        "yuyuPrice": 80,
        "marketPrice": 0.57
      },
      {
        "cardId": "OP02-117",
        "name": "Ice Age",
        "quantity": 4,
        "cost": 1,
        "power": null,
        "category": "Event",
        "colors": "Black",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op02/10148.jpg",
        "yuyuPrice": 80,
        "marketPrice": 0.57
      },
      {
        "cardId": "OP06-096",
        "name": "...Nothing...at All!!!",
        "quantity": 2,
        "cost": 3,
        "power": null,
        "category": "Event",
        "colors": "Black",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op06/10115.jpg",
        "yuyuPrice": 30,
        "marketPrice": 0.21
      }
    ],
    "stats": {
      "charactersCount": 36,
      "eventsCount": 14,
      "stagesCount": 0,
      "counters2000": 8,
      "counters1000": 16,
      "noCounter": 26,
      "avgCost": 4
    }
  },
  {
    "id": "green-jewelry-bonney-op07",
    "name": "(Green) Jewelry Bonney",
    "subname": "Supernovas Fortress",
    "leaderId": "OP07-019",
    "leaderName": "Jewelry Bonney",
    "leaderImage": "https://card.yuyu-tei.jp/opc/front/op07/10022.jpg",
    "color": "Green",
    "colorDot": "#22c55e",
    "rank": "#1 Tier 1",
    "winrate": "62.5%",
    "date": "15/09/2026",
    "tournament": "Bandai Card Fest Cup Champion",
    "source": "OnePieceTopDecks",
    "metaEra": "OP-08",
    "tier": "Tier 1",
    "description": "Premier defensive Fortress deck. Rest-locks the opponent leader with Bonney ability, then builds an impenetrable wall with 8-cost Kid, Cavendish, and Hawkins.",
    "cards": [
      {
        "cardId": "OP07-022",
        "name": "Otama",
        "quantity": 4,
        "cost": 1,
        "power": null,
        "category": "Character",
        "colors": "Green",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op07/10026.jpg",
        "yuyuPrice": 120,
        "marketPrice": 0.86
      },
      {
        "cardId": "ST02-007",
        "name": "Jewelry Bonney",
        "quantity": 4,
        "cost": 1,
        "power": 1000,
        "category": "Character",
        "colors": "Green",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/prb02/10104.jpg",
        "yuyuPrice": 80,
        "marketPrice": 0.57
      },
      {
        "cardId": "OP01-051",
        "name": "Eustass\"Captain\"Kid",
        "quantity": 4,
        "cost": 8,
        "power": 8000,
        "category": "Character",
        "colors": "Green",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op01/10064.jpg",
        "yuyuPrice": 120,
        "marketPrice": 0.86
      },
      {
        "cardId": "OP02-036",
        "name": "Nami",
        "quantity": 4,
        "cost": 3,
        "power": 5000,
        "category": "Character",
        "colors": "Green",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op02/10048.jpg",
        "yuyuPrice": 320,
        "marketPrice": 2.29
      },
      {
        "cardId": "OP04-032",
        "name": "Baby 5",
        "quantity": 4,
        "cost": 1,
        "power": 1000,
        "category": "Character",
        "colors": "Green",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/prb01/10081.jpg",
        "yuyuPrice": 80,
        "marketPrice": 0.57
      },
      {
        "cardId": "OP01-039",
        "name": "Killer",
        "quantity": 4,
        "cost": 2,
        "power": 2000,
        "category": "Character",
        "colors": "Green",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/prb02/10037.jpg",
        "yuyuPrice": 80,
        "marketPrice": 0.57
      },
      {
        "cardId": "OP01-041",
        "name": "Kouzuki Momonosuke",
        "quantity": 4,
        "cost": 1,
        "power": null,
        "category": "Character",
        "colors": "Green",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op01/10052.jpg",
        "yuyuPrice": 80,
        "marketPrice": 0.57
      },
      {
        "cardId": "OP01-047",
        "name": "Trafalgar Law",
        "quantity": 4,
        "cost": 5,
        "power": 6000,
        "category": "Character",
        "colors": "Green",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op01/10058.jpg",
        "yuyuPrice": 120,
        "marketPrice": 0.86
      },
      {
        "cardId": "OP02-040",
        "name": "Brook",
        "quantity": 4,
        "cost": 4,
        "power": 5000,
        "category": "Character",
        "colors": "Green",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op02/10053.jpg",
        "yuyuPrice": 80,
        "marketPrice": 0.57
      },
      {
        "cardId": "OP01-054",
        "name": "X.Drake",
        "quantity": 4,
        "cost": 5,
        "power": 6000,
        "category": "Character",
        "colors": "Green",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op01/10068.jpg",
        "yuyuPrice": 80,
        "marketPrice": 0.57
      },
      {
        "cardId": "OP01-057",
        "name": "Paradise Waterfall",
        "quantity": 4,
        "cost": 1,
        "power": null,
        "category": "Event",
        "colors": "Green",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op01/10071.jpg",
        "yuyuPrice": 80,
        "marketPrice": 0.57
      },
      {
        "cardId": "OP01-058",
        "name": "Punk Gibson",
        "quantity": 4,
        "cost": 2,
        "power": null,
        "category": "Event",
        "colors": "Green",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op01/10072.jpg",
        "yuyuPrice": 120,
        "marketPrice": 0.86
      },
      {
        "cardId": "ST02-014",
        "name": "X.Drake",
        "quantity": 2,
        "cost": 4,
        "power": 5000,
        "category": "Character",
        "colors": "Green",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/st02/10014.jpg",
        "yuyuPrice": 80,
        "marketPrice": 0.57
      }
    ],
    "stats": {
      "charactersCount": 42,
      "eventsCount": 8,
      "stagesCount": 0,
      "counters2000": 8,
      "counters1000": 22,
      "noCounter": 20,
      "avgCost": 2.9
    }
  },
  {
    "id": "yellow-enel-op05",
    "name": "(Yellow) Enel",
    "subname": "Sky Island God of Skypiea",
    "leaderId": "OP05-098",
    "leaderName": "Enel",
    "leaderImage": "https://card.yuyu-tei.jp/opc/front/op05/10119.jpg",
    "color": "Yellow",
    "colorDot": "#facc15",
    "rank": "#2 Tier 1",
    "winrate": "61.7%",
    "date": "14/09/2026",
    "tournament": "Treasure Cup Champion",
    "source": "OnePieceTopDecks",
    "metaEra": "OP-08",
    "tier": "Tier 1",
    "description": "Virtually immortal life-gain engine. Enel passive resurrects from 0 to 1 life every turn, backed by Gedatsu removal, Ohm combos, and 9-cost Yamato.",
    "cards": [
      {
        "cardId": "OP05-102",
        "name": "Gedatsu",
        "quantity": 4,
        "cost": 5,
        "power": 6000,
        "category": "Character",
        "colors": "Yellow",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op05/10125.jpg",
        "yuyuPrice": 80,
        "marketPrice": 0.57
      },
      {
        "cardId": "OP05-100",
        "name": "Enel",
        "quantity": 4,
        "cost": 7,
        "power": 7000,
        "category": "Character",
        "colors": "Yellow",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op05/10122.jpg",
        "yuyuPrice": 220,
        "marketPrice": 1.57
      },
      {
        "cardId": "OP05-101",
        "name": "Ohm",
        "quantity": 4,
        "cost": 4,
        "power": 5000,
        "category": "Character",
        "colors": "Yellow",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op05/10124.jpg",
        "yuyuPrice": 120,
        "marketPrice": 0.86
      },
      {
        "cardId": "OP05-110",
        "name": "Holly",
        "quantity": 4,
        "cost": 3,
        "power": 5000,
        "category": "Character",
        "colors": "Yellow",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op05/10134.jpg",
        "yuyuPrice": 30,
        "marketPrice": 0.21
      },
      {
        "cardId": "OP04-112",
        "name": "Yamato",
        "quantity": 4,
        "cost": 9,
        "power": 9000,
        "category": "Character",
        "colors": "Yellow",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op04/10134.jpg",
        "yuyuPrice": 120,
        "marketPrice": 0.86
      },
      {
        "cardId": "OP03-123",
        "name": "Charlotte Katakuri",
        "quantity": 4,
        "cost": 8,
        "power": 8000,
        "category": "Character",
        "colors": "Yellow",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/prb01/10076.jpg",
        "yuyuPrice": 220,
        "marketPrice": 1.57
      },
      {
        "cardId": "OP03-112",
        "name": "Charlotte Pudding",
        "quantity": 4,
        "cost": 1,
        "power": 2000,
        "category": "Character",
        "colors": "Yellow",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/st20/10008.jpg",
        "yuyuPrice": 50,
        "marketPrice": 0.36
      },
      {
        "cardId": "OP03-114",
        "name": "Charlotte Linlin",
        "quantity": 4,
        "cost": 10,
        "power": 12000,
        "category": "Character",
        "colors": "Yellow",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op03/10137.jpg",
        "yuyuPrice": 220,
        "marketPrice": 1.57
      },
      {
        "cardId": "OP05-106",
        "name": "Shura",
        "quantity": 4,
        "cost": 2,
        "power": 2000,
        "category": "Character",
        "colors": "Yellow",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op05/10130.jpg",
        "yuyuPrice": 80,
        "marketPrice": 0.57
      },
      {
        "cardId": "OP05-105",
        "name": "Satori",
        "quantity": 4,
        "cost": 5,
        "power": 5000,
        "category": "Character",
        "colors": "Yellow",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/prb01/10123.jpg",
        "yuyuPrice": 120,
        "marketPrice": 0.86
      },
      {
        "cardId": "OP05-115",
        "name": "Two-Hundred Million Volts Amaru",
        "quantity": 4,
        "cost": 2,
        "power": null,
        "category": "Event",
        "colors": "Yellow",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op05/10139.jpg",
        "yuyuPrice": 80,
        "marketPrice": 0.57
      },
      {
        "cardId": "OP03-121",
        "name": "Thunder Bolt",
        "quantity": 4,
        "cost": 2,
        "power": null,
        "category": "Event",
        "colors": "Yellow",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op03/10145.jpg",
        "yuyuPrice": 30,
        "marketPrice": 0.21
      },
      {
        "cardId": "OP05-114",
        "name": "El Thor",
        "quantity": 2,
        "cost": 1,
        "power": null,
        "category": "Event",
        "colors": "Yellow",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/prb01/10126.jpg",
        "yuyuPrice": 80,
        "marketPrice": 0.57
      }
    ],
    "stats": {
      "charactersCount": 40,
      "eventsCount": 10,
      "stagesCount": 0,
      "counters2000": 4,
      "counters1000": 20,
      "noCounter": 26,
      "avgCost": 4.7
    }
  },
  {
    "id": "red-blue-marco-op08",
    "name": "(Red/Blue) Marco",
    "subname": "Whitebeard Pirates & Seven Warlords",
    "leaderId": "OP08-002",
    "leaderName": "Marco",
    "leaderImage": "https://card.yuyu-tei.jp/opc/front/op08/10003.jpg",
    "color": "Red",
    "colorDot": "#ef4444",
    "rank": "#2 Tier 1",
    "winrate": "60.4%",
    "date": "12/09/2026",
    "tournament": "Standard Battle Champion",
    "source": "OnePieceTopDecks",
    "metaEra": "OP-08",
    "tier": "Tier 1",
    "description": "Hybrid midrange blending Red aggressive pressure (Edward.Newgate, Ace, Vista) with Blue hand filtering and Overheat/Red Roc removal.",
    "cards": [
      {
        "cardId": "OP02-004",
        "name": "Edward.Newgate",
        "quantity": 4,
        "cost": 9,
        "power": 10000,
        "category": "Character",
        "colors": "Red",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op02/10006.jpg",
        "yuyuPrice": 120,
        "marketPrice": 0.86
      },
      {
        "cardId": "OP02-018",
        "name": "Marco",
        "quantity": 4,
        "cost": 4,
        "power": 5000,
        "category": "Character",
        "colors": "Red",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/st15/10008.jpg",
        "yuyuPrice": 50,
        "marketPrice": 0.36
      },
      {
        "cardId": "OP03-003",
        "name": "Izo",
        "quantity": 4,
        "cost": 1,
        "power": 2000,
        "category": "Character",
        "colors": "Red",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/st15/10009.jpg",
        "yuyuPrice": 50,
        "marketPrice": 0.36
      },
      {
        "cardId": "OP02-013",
        "name": "Portgas.D.Ace",
        "quantity": 4,
        "cost": 7,
        "power": 7000,
        "category": "Character",
        "colors": "Red",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op02/10017.jpg",
        "yuyuPrice": 220,
        "marketPrice": 1.57
      },
      {
        "cardId": "OP02-011",
        "name": "Vista",
        "quantity": 4,
        "cost": 3,
        "power": 3000,
        "category": "Character",
        "colors": "Red",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op02/10015.jpg",
        "yuyuPrice": 80,
        "marketPrice": 0.57
      },
      {
        "cardId": "OP02-008",
        "name": "Jozu",
        "quantity": 4,
        "cost": 4,
        "power": 4000,
        "category": "Character",
        "colors": "Red",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/st15/10007.jpg",
        "yuyuPrice": 50,
        "marketPrice": 0.36
      },
      {
        "cardId": "OP01-073",
        "name": "Donquixote Doflamingo",
        "quantity": 4,
        "cost": 3,
        "power": 4000,
        "category": "Character",
        "colors": "Blue",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/st17/10007.jpg",
        "yuyuPrice": 50,
        "marketPrice": 0.36
      },
      {
        "cardId": "OP01-078",
        "name": "Boa Hancock",
        "quantity": 4,
        "cost": 4,
        "power": 5000,
        "category": "Character",
        "colors": "Blue",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op01/10100.jpg",
        "yuyuPrice": 120,
        "marketPrice": 0.86
      },
      {
        "cardId": "OP03-044",
        "name": "Kaya",
        "quantity": 4,
        "cost": 1,
        "power": null,
        "category": "Character",
        "colors": "Blue",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op03/10053.jpg",
        "yuyuPrice": 220,
        "marketPrice": 1.57
      },
      {
        "cardId": "OP02-054",
        "name": "Gecko Moria",
        "quantity": 4,
        "cost": 4,
        "power": 6000,
        "category": "Character",
        "colors": "Blue",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op02/10070.jpg",
        "yuyuPrice": 80,
        "marketPrice": 0.57
      },
      {
        "cardId": "OP01-086",
        "name": "Overheat",
        "quantity": 4,
        "cost": 2,
        "power": null,
        "category": "Event",
        "colors": "Blue",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/st17/10008.jpg",
        "yuyuPrice": 50,
        "marketPrice": 0.36
      },
      {
        "cardId": "OP02-024",
        "name": "Moby Dick",
        "quantity": 4,
        "cost": 2,
        "power": null,
        "category": "Stage",
        "colors": "Red",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op02/10032.jpg",
        "yuyuPrice": 120,
        "marketPrice": 0.86
      },
      {
        "cardId": "OP01-029",
        "name": "Radical Beam!!",
        "quantity": 2,
        "cost": 1,
        "power": null,
        "category": "Event",
        "colors": "Red",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op01/10037.jpg",
        "yuyuPrice": 80,
        "marketPrice": 0.57
      }
    ],
    "stats": {
      "charactersCount": 40,
      "eventsCount": 6,
      "stagesCount": 4,
      "counters2000": 8,
      "counters1000": 24,
      "noCounter": 18,
      "avgCost": 3.6
    }
  },
  {
    "id": "red-shanks-op09",
    "name": "(Red) Shanks",
    "subname": "Red Hair Pirates",
    "leaderId": "OP09-001",
    "leaderName": "Shanks",
    "leaderImage": "https://card.yuyu-tei.jp/opc/front/op09/10001.jpg",
    "color": "Red",
    "colorDot": "#dc2626",
    "rank": "#2 Tier 1",
    "winrate": "61.9%",
    "date": "21/09/2026",
    "tournament": "Championship Yokohama Champion",
    "source": "OnePieceTopDecks",
    "metaEra": "OP-09",
    "tier": "Tier 1",
    "description": "Top-tier aggressive Emperor deck. Blazes through opponent defenses with 10-cost Shanks, Benn Beckman, Yasopp, and Divine Departure.",
    "cards": [
      {
        "cardId": "OP09-004",
        "name": "Shanks",
        "quantity": 4,
        "cost": 10,
        "power": 12000,
        "category": "Character",
        "colors": "Red",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op09/10006.jpg",
        "yuyuPrice": 120,
        "marketPrice": 0.86
      },
      {
        "cardId": "OP09-013",
        "name": "Yasopp",
        "quantity": 4,
        "cost": 5,
        "power": 6000,
        "category": "Character",
        "colors": "Red",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/st23/10007.jpg",
        "yuyuPrice": 50,
        "marketPrice": 0.36
      },
      {
        "cardId": "OP09-014",
        "name": "Limejuice",
        "quantity": 4,
        "cost": 3,
        "power": 3000,
        "category": "Character",
        "colors": "Red",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/prb02/10078.jpg",
        "yuyuPrice": 80,
        "marketPrice": 0.57
      },
      {
        "cardId": "OP09-015",
        "name": "Lucky.Roux",
        "quantity": 4,
        "cost": 4,
        "power": 5000,
        "category": "Character",
        "colors": "Red",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/st23/10008.jpg",
        "yuyuPrice": 50,
        "marketPrice": 0.36
      },
      {
        "cardId": "OP09-003",
        "name": "Shachi & Penguin",
        "quantity": 4,
        "cost": 4,
        "power": 5000,
        "category": "Character",
        "colors": "Red",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op09/10005.jpg",
        "yuyuPrice": 30,
        "marketPrice": 0.21
      },
      {
        "cardId": "OP01-016",
        "name": "Nami",
        "quantity": 4,
        "cost": 1,
        "power": 2000,
        "category": "Character",
        "colors": "Red",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/st31/10006.jpg",
        "yuyuPrice": 120,
        "marketPrice": 0.86
      },
      {
        "cardId": "OP01-006",
        "name": "Otama",
        "quantity": 4,
        "cost": 1,
        "power": null,
        "category": "Character",
        "colors": "Red",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op01/10009.jpg",
        "yuyuPrice": 120,
        "marketPrice": 0.86
      },
      {
        "cardId": "OP01-013",
        "name": "Sanji",
        "quantity": 4,
        "cost": 2,
        "power": 3000,
        "category": "Character",
        "colors": "Red",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op01/10017.jpg",
        "yuyuPrice": 120,
        "marketPrice": 0.86
      },
      {
        "cardId": "OP01-025",
        "name": "Roronoa Zoro",
        "quantity": 4,
        "cost": 3,
        "power": 5000,
        "category": "Character",
        "colors": "Red",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op01/10032.jpg",
        "yuyuPrice": 220,
        "marketPrice": 1.57
      },
      {
        "cardId": "OP02-005",
        "name": "Curly.Dadan",
        "quantity": 4,
        "cost": 2,
        "power": 3000,
        "category": "Character",
        "colors": "Red",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/prb02/10039.jpg",
        "yuyuPrice": 80,
        "marketPrice": 0.57
      },
      {
        "cardId": "OP09-018",
        "name": "Get Out of Here!",
        "quantity": 4,
        "cost": 3,
        "power": null,
        "category": "Event",
        "colors": "Red",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op09/10023.jpg",
        "yuyuPrice": 80,
        "marketPrice": 0.57
      },
      {
        "cardId": "OP01-029",
        "name": "Radical Beam!!",
        "quantity": 4,
        "cost": 1,
        "power": null,
        "category": "Event",
        "colors": "Red",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op01/10037.jpg",
        "yuyuPrice": 80,
        "marketPrice": 0.57
      },
      {
        "cardId": "OP01-030",
        "name": "In Two Years!! At the Sabaody Archipelago!!",
        "quantity": 2,
        "cost": 1,
        "power": null,
        "category": "Event",
        "colors": "Red",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op01/10038.jpg",
        "yuyuPrice": 80,
        "marketPrice": 0.57
      }
    ],
    "stats": {
      "charactersCount": 40,
      "eventsCount": 10,
      "stagesCount": 0,
      "counters2000": 12,
      "counters1000": 20,
      "noCounter": 18,
      "avgCost": 3.2
    }
  },
  {
    "id": "black-gecko-moria-op06",
    "name": "(Black) Gecko Moria",
    "subname": "Thriller Bark Pirates",
    "leaderId": "OP06-080",
    "leaderName": "Gecko Moria",
    "leaderImage": "https://card.yuyu-tei.jp/opc/front/op06/10095.jpg",
    "color": "Black",
    "colorDot": "#334155",
    "rank": "#3 Tier 1.5",
    "winrate": "59.8%",
    "date": "08/09/2026",
    "tournament": "Flagship Battle Finalist",
    "source": "OnePieceTopDecks",
    "metaEra": "OP-08",
    "tier": "Tier 1.5",
    "description": "Master of trash recursion. Revives combo pieces with Hogback, Absalom, and Perona while dropping 8-cost Gecko Moria for overwhelming board state.",
    "cards": [
      {
        "cardId": "OP06-086",
        "name": "Gecko Moria",
        "quantity": 4,
        "cost": 8,
        "power": 9000,
        "category": "Character",
        "colors": "Black",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op06/10103.jpg",
        "yuyuPrice": 120,
        "marketPrice": 0.86
      },
      {
        "cardId": "OP06-093",
        "name": "Perona",
        "quantity": 4,
        "cost": 4,
        "power": 5000,
        "category": "Character",
        "colors": "Black",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op06/10111.jpg",
        "yuyuPrice": 220,
        "marketPrice": 1.57
      },
      {
        "cardId": "OP06-091",
        "name": "Victoria Cindry",
        "quantity": 4,
        "cost": 1,
        "power": 2000,
        "category": "Character",
        "colors": "Black",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/prb01/10168.jpg",
        "yuyuPrice": 80,
        "marketPrice": 0.57
      },
      {
        "cardId": "OP06-081",
        "name": "Absalom",
        "quantity": 4,
        "cost": 4,
        "power": 5000,
        "category": "Character",
        "colors": "Black",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op06/10097.jpg",
        "yuyuPrice": 120,
        "marketPrice": 0.86
      },
      {
        "cardId": "OP06-087",
        "name": "Cerberus",
        "quantity": 4,
        "cost": 2,
        "power": 2000,
        "category": "Character",
        "colors": "Black",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op06/10105.jpg",
        "yuyuPrice": 30,
        "marketPrice": 0.21
      },
      {
        "cardId": "OP06-092",
        "name": "Brook",
        "quantity": 4,
        "cost": 6,
        "power": 6000,
        "category": "Character",
        "colors": "Black",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op06/10110.jpg",
        "yuyuPrice": 80,
        "marketPrice": 0.57
      },
      {
        "cardId": "OP05-091",
        "name": "Rebecca",
        "quantity": 4,
        "cost": 4,
        "power": null,
        "category": "Character",
        "colors": "Black",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op05/10110.jpg",
        "yuyuPrice": 180,
        "marketPrice": 1.29
      },
      {
        "cardId": "OP03-089",
        "name": "Brannew",
        "quantity": 4,
        "cost": 2,
        "power": 3000,
        "category": "Character",
        "colors": "Black",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/st19/10008.jpg",
        "yuyuPrice": 50,
        "marketPrice": 0.36
      },
      {
        "cardId": "OP02-096",
        "name": "Kuzan",
        "quantity": 4,
        "cost": 4,
        "power": 5000,
        "category": "Character",
        "colors": "Black",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op02/10121.jpg",
        "yuyuPrice": 120,
        "marketPrice": 0.86
      },
      {
        "cardId": "OP06-090",
        "name": "Dr. Hogback",
        "quantity": 4,
        "cost": 4,
        "power": 5000,
        "category": "Character",
        "colors": "Black",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op06/10108.jpg",
        "yuyuPrice": 120,
        "marketPrice": 0.86
      },
      {
        "cardId": "OP02-117",
        "name": "Ice Age",
        "quantity": 4,
        "cost": 1,
        "power": null,
        "category": "Event",
        "colors": "Black",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op02/10148.jpg",
        "yuyuPrice": 80,
        "marketPrice": 0.57
      },
      {
        "cardId": "OP06-096",
        "name": "...Nothing...at All!!!",
        "quantity": 4,
        "cost": 3,
        "power": null,
        "category": "Event",
        "colors": "Black",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op06/10115.jpg",
        "yuyuPrice": 30,
        "marketPrice": 0.21
      },
      {
        "cardId": "OP02-114",
        "name": "Borsalino",
        "quantity": 2,
        "cost": 4,
        "power": 5000,
        "category": "Character",
        "colors": "Black",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op02/10143.jpg",
        "yuyuPrice": 120,
        "marketPrice": 0.86
      }
    ],
    "stats": {
      "charactersCount": 42,
      "eventsCount": 8,
      "stagesCount": 0,
      "counters2000": 8,
      "counters1000": 22,
      "noCounter": 20,
      "avgCost": 3.6
    }
  },
  {
    "id": "green-yellow-yamato-op06",
    "name": "(Green/Yellow) Yamato",
    "subname": "Land of Wano & Sky Island",
    "leaderId": "OP06-022",
    "leaderName": "Yamato",
    "leaderImage": "https://card.yuyu-tei.jp/opc/front/op06/10028.jpg",
    "color": "Green",
    "colorDot": "#84cc16",
    "rank": "#3 Tier 1.5",
    "winrate": "58.9%",
    "date": "05/09/2026",
    "tournament": "Store Championship 1st Place",
    "source": "OnePieceTopDecks",
    "metaEra": "OP-08",
    "tier": "Tier 1.5",
    "description": "Fast dual-attack leader threat with Onami Banish and You Can Be My Samurai!! life-manipulation, closing matches with 9-cost Yamato and Hody Jones.",
    "cards": [
      {
        "cardId": "OP06-106",
        "name": "Kouzuki Hiyori",
        "quantity": 4,
        "cost": 2,
        "power": null,
        "category": "Character",
        "colors": "Yellow",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op06/10126.jpg",
        "yuyuPrice": 120,
        "marketPrice": 0.86
      },
      {
        "cardId": "OP06-107",
        "name": "Kouzuki Momonosuke",
        "quantity": 4,
        "cost": 5,
        "power": 6000,
        "category": "Character",
        "colors": "Yellow",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op06/10128.jpg",
        "yuyuPrice": 80,
        "marketPrice": 0.57
      },
      {
        "cardId": "OP06-101",
        "name": "O-Nami",
        "quantity": 4,
        "cost": 2,
        "power": 3000,
        "category": "Character",
        "colors": "Yellow",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op06/10120.jpg",
        "yuyuPrice": 180,
        "marketPrice": 1.29
      },
      {
        "cardId": "OP05-101",
        "name": "Ohm",
        "quantity": 4,
        "cost": 4,
        "power": 5000,
        "category": "Character",
        "colors": "Yellow",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op05/10124.jpg",
        "yuyuPrice": 120,
        "marketPrice": 0.86
      },
      {
        "cardId": "OP05-110",
        "name": "Holly",
        "quantity": 4,
        "cost": 3,
        "power": 5000,
        "category": "Character",
        "colors": "Yellow",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op05/10134.jpg",
        "yuyuPrice": 30,
        "marketPrice": 0.21
      },
      {
        "cardId": "OP04-112",
        "name": "Yamato",
        "quantity": 4,
        "cost": 9,
        "power": 9000,
        "category": "Character",
        "colors": "Yellow",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op04/10134.jpg",
        "yuyuPrice": 120,
        "marketPrice": 0.86
      },
      {
        "cardId": "OP06-035",
        "name": "Hody Jones",
        "quantity": 4,
        "cost": 7,
        "power": 8000,
        "category": "Character",
        "colors": "Green",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op06/10043.jpg",
        "yuyuPrice": 120,
        "marketPrice": 0.86
      },
      {
        "cardId": "OP01-051",
        "name": "Eustass\"Captain\"Kid",
        "quantity": 4,
        "cost": 8,
        "power": 8000,
        "category": "Character",
        "colors": "Green",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op01/10064.jpg",
        "yuyuPrice": 120,
        "marketPrice": 0.86
      },
      {
        "cardId": "ST02-007",
        "name": "Jewelry Bonney",
        "quantity": 4,
        "cost": 1,
        "power": 1000,
        "category": "Character",
        "colors": "Green",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/prb02/10104.jpg",
        "yuyuPrice": 80,
        "marketPrice": 0.57
      },
      {
        "cardId": "OP02-036",
        "name": "Nami",
        "quantity": 4,
        "cost": 3,
        "power": 5000,
        "category": "Character",
        "colors": "Green",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op02/10048.jpg",
        "yuyuPrice": 320,
        "marketPrice": 2.29
      },
      {
        "cardId": "OP05-115",
        "name": "Two-Hundred Million Volts Amaru",
        "quantity": 4,
        "cost": 2,
        "power": null,
        "category": "Event",
        "colors": "Yellow",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op05/10139.jpg",
        "yuyuPrice": 80,
        "marketPrice": 0.57
      },
      {
        "cardId": "OP06-115",
        "name": "You're the One Who Should Disappear.",
        "quantity": 4,
        "cost": null,
        "power": null,
        "category": "Event",
        "colors": "Yellow",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op06/10137.jpg",
        "yuyuPrice": 120,
        "marketPrice": 0.86
      },
      {
        "cardId": "OP01-058",
        "name": "Punk Gibson",
        "quantity": 2,
        "cost": 2,
        "power": null,
        "category": "Event",
        "colors": "Green",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op01/10072.jpg",
        "yuyuPrice": 120,
        "marketPrice": 0.86
      }
    ],
    "stats": {
      "charactersCount": 40,
      "eventsCount": 10,
      "stagesCount": 0,
      "counters2000": 4,
      "counters1000": 16,
      "noCounter": 30,
      "avgCost": 4.1
    }
  },
  {
    "id": "red-purple-monkey-d-luffy-st10",
    "name": "(Red/Purple) Monkey.D.Luffy",
    "subname": "The Three Captains & Straw Hat Crew",
    "leaderId": "ST10-002",
    "leaderName": "Monkey.D.Luffy",
    "leaderImage": "https://card.yuyu-tei.jp/opc/front/st10/10002.jpg",
    "color": "Purple",
    "colorDot": "#9333ea",
    "rank": "#3 Tier 1.5",
    "winrate": "58.4%",
    "date": "02/09/2026",
    "tournament": "Flagship Battle Champion",
    "source": "OnePieceTopDecks",
    "metaEra": "OP-08",
    "tier": "Tier 1.5",
    "description": "High-tempo DON!! ramping engine accelerating into 10-cost Gear 5 Luffy, 7-cost Kid, and Jean Bart with defensive Red counters.",
    "cards": [
      {
        "cardId": "ST10-006",
        "name": "Monkey.D.Luffy",
        "quantity": 4,
        "cost": 10,
        "power": 11000,
        "category": "Character",
        "colors": "Red",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/st10/10006.jpg",
        "yuyuPrice": 220,
        "marketPrice": 1.57
      },
      {
        "cardId": "OP05-119",
        "name": "Monkey.D.Luffy",
        "quantity": 4,
        "cost": 10,
        "power": 12000,
        "category": "Character",
        "colors": "Purple",
        "imageUrl": "https://onepiece-cardgame.com/images/cardlist/card/OP05-119.png?260828",
        "yuyuPrice": 780,
        "marketPrice": 38
      },
      {
        "cardId": "ST10-013",
        "name": "Eustass\"Captain\"Kid",
        "quantity": 4,
        "cost": 7,
        "power": 8000,
        "category": "Character",
        "colors": "Purple",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/st10/10013.jpg",
        "yuyuPrice": 220,
        "marketPrice": 1.57
      },
      {
        "cardId": "ST10-010",
        "name": "Trafalgar Law",
        "quantity": 4,
        "cost": 4,
        "power": 5000,
        "category": "Character",
        "colors": "Purple",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/st10/10010.jpg",
        "yuyuPrice": 120,
        "marketPrice": 0.86
      },
      {
        "cardId": "ST10-008",
        "name": "Shachi & Penguin",
        "quantity": 4,
        "cost": 4,
        "power": 5000,
        "category": "Character",
        "colors": "Purple",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/prb02/10108.jpg",
        "yuyuPrice": 50,
        "marketPrice": 0.36
      },
      {
        "cardId": "ST10-005",
        "name": "Jinbe",
        "quantity": 4,
        "cost": 2,
        "power": 2000,
        "category": "Character",
        "colors": "Red",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/prb02/10106.jpg",
        "yuyuPrice": 50,
        "marketPrice": 0.36
      },
      {
        "cardId": "OP01-016",
        "name": "Nami",
        "quantity": 4,
        "cost": 1,
        "power": 2000,
        "category": "Character",
        "colors": "Red",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/st31/10006.jpg",
        "yuyuPrice": 120,
        "marketPrice": 0.86
      },
      {
        "cardId": "OP01-006",
        "name": "Otama",
        "quantity": 4,
        "cost": 1,
        "power": null,
        "category": "Character",
        "colors": "Red",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op01/10009.jpg",
        "yuyuPrice": 120,
        "marketPrice": 0.86
      },
      {
        "cardId": "OP01-025",
        "name": "Roronoa Zoro",
        "quantity": 4,
        "cost": 3,
        "power": 5000,
        "category": "Character",
        "colors": "Red",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op01/10032.jpg",
        "yuyuPrice": 220,
        "marketPrice": 1.57
      },
      {
        "cardId": "OP02-005",
        "name": "Curly.Dadan",
        "quantity": 4,
        "cost": 2,
        "power": 3000,
        "category": "Character",
        "colors": "Red",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/prb02/10039.jpg",
        "yuyuPrice": 80,
        "marketPrice": 0.57
      },
      {
        "cardId": "OP01-029",
        "name": "Radical Beam!!",
        "quantity": 4,
        "cost": 1,
        "power": null,
        "category": "Event",
        "colors": "Red",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op01/10037.jpg",
        "yuyuPrice": 80,
        "marketPrice": 0.57
      },
      {
        "cardId": "OP01-030",
        "name": "In Two Years!! At the Sabaody Archipelago!!",
        "quantity": 4,
        "cost": 1,
        "power": null,
        "category": "Event",
        "colors": "Red",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op01/10038.jpg",
        "yuyuPrice": 80,
        "marketPrice": 0.57
      },
      {
        "cardId": "ST10-016",
        "name": "Gum-Gum Kong Gatling",
        "quantity": 2,
        "cost": 5,
        "power": null,
        "category": "Event",
        "colors": "Red",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/st10/10016.jpg",
        "yuyuPrice": 120,
        "marketPrice": 0.86
      }
    ],
    "stats": {
      "charactersCount": 40,
      "eventsCount": 10,
      "stagesCount": 0,
      "counters2000": 12,
      "counters1000": 12,
      "noCounter": 26,
      "avgCost": 3.9
    }
  },
  {
    "id": "red-roronoa-zoro-op01",
    "name": "(Red) Roronoa Zoro",
    "subname": "Straw Hat Aggro Rush",
    "leaderId": "OP01-001",
    "leaderName": "Roronoa Zoro",
    "leaderImage": "https://card.yuyu-tei.jp/opc/front/op01/10001.jpg",
    "color": "Red",
    "colorDot": "#e11d48",
    "rank": "#4 Tier 1.5",
    "winrate": "56.5%",
    "date": "25/08/2026",
    "tournament": "Local Store Championship 1st Place",
    "source": "OnePieceTopDecks",
    "metaEra": "OP-08",
    "tier": "Tier 1.5",
    "description": "The definitive aggro archetype. Every character gains +1000 power for 1 DON!!, constantly applying unrelenting lethal pressure with Zoro, Marco, and Dadan.",
    "cards": [
      {
        "cardId": "OP01-025",
        "name": "Roronoa Zoro",
        "quantity": 4,
        "cost": 3,
        "power": 5000,
        "category": "Character",
        "colors": "Red",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op01/10032.jpg",
        "yuyuPrice": 220,
        "marketPrice": 1.57
      },
      {
        "cardId": "OP02-018",
        "name": "Marco",
        "quantity": 4,
        "cost": 4,
        "power": 5000,
        "category": "Character",
        "colors": "Red",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/st15/10008.jpg",
        "yuyuPrice": 50,
        "marketPrice": 0.36
      },
      {
        "cardId": "OP01-016",
        "name": "Nami",
        "quantity": 4,
        "cost": 1,
        "power": 2000,
        "category": "Character",
        "colors": "Red",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/st31/10006.jpg",
        "yuyuPrice": 120,
        "marketPrice": 0.86
      },
      {
        "cardId": "OP01-006",
        "name": "Otama",
        "quantity": 4,
        "cost": 1,
        "power": null,
        "category": "Character",
        "colors": "Red",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op01/10009.jpg",
        "yuyuPrice": 120,
        "marketPrice": 0.86
      },
      {
        "cardId": "OP01-013",
        "name": "Sanji",
        "quantity": 4,
        "cost": 2,
        "power": 3000,
        "category": "Character",
        "colors": "Red",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op01/10017.jpg",
        "yuyuPrice": 120,
        "marketPrice": 0.86
      },
      {
        "cardId": "OP02-005",
        "name": "Curly.Dadan",
        "quantity": 4,
        "cost": 2,
        "power": 3000,
        "category": "Character",
        "colors": "Red",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/prb02/10039.jpg",
        "yuyuPrice": 80,
        "marketPrice": 0.57
      },
      {
        "cardId": "OP01-017",
        "name": "Nico Robin",
        "quantity": 4,
        "cost": 3,
        "power": 4000,
        "category": "Character",
        "colors": "Red",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op01/10023.jpg",
        "yuyuPrice": 80,
        "marketPrice": 0.57
      },
      {
        "cardId": "OP01-009",
        "name": "Carrot",
        "quantity": 4,
        "cost": 2,
        "power": 3000,
        "category": "Character",
        "colors": "Red",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op01/10013.jpg",
        "yuyuPrice": 30,
        "marketPrice": 0.21
      },
      {
        "cardId": "OP02-011",
        "name": "Vista",
        "quantity": 4,
        "cost": 3,
        "power": 3000,
        "category": "Character",
        "colors": "Red",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op02/10015.jpg",
        "yuyuPrice": 80,
        "marketPrice": 0.57
      },
      {
        "cardId": "OP01-027",
        "name": "Round Table",
        "quantity": 4,
        "cost": 4,
        "power": null,
        "category": "Event",
        "colors": "Red",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op01/10035.jpg",
        "yuyuPrice": 80,
        "marketPrice": 0.57
      },
      {
        "cardId": "OP01-029",
        "name": "Radical Beam!!",
        "quantity": 4,
        "cost": 1,
        "power": null,
        "category": "Event",
        "colors": "Red",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op01/10037.jpg",
        "yuyuPrice": 80,
        "marketPrice": 0.57
      },
      {
        "cardId": "OP01-030",
        "name": "In Two Years!! At the Sabaody Archipelago!!",
        "quantity": 4,
        "cost": 1,
        "power": null,
        "category": "Event",
        "colors": "Red",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op01/10038.jpg",
        "yuyuPrice": 80,
        "marketPrice": 0.57
      },
      {
        "cardId": "OP02-021",
        "name": "Seaquake",
        "quantity": 2,
        "cost": 1,
        "power": null,
        "category": "Event",
        "colors": "Red",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op02/10029.jpg",
        "yuyuPrice": 120,
        "marketPrice": 0.86
      }
    ],
    "stats": {
      "charactersCount": 36,
      "eventsCount": 14,
      "stagesCount": 0,
      "counters2000": 8,
      "counters1000": 24,
      "noCounter": 18,
      "avgCost": 2.2
    }
  },
  {
    "id": "yellow-charlotte-linlin-op17",
    "name": "(Yellow) Charlotte Linlin",
    "subname": "Big Mom Pirates Trigger Control",
    "leaderId": "OP17-099",
    "leaderName": "Charlotte Linlin",
    "leaderImage": "https://card.yuyu-tei.jp/opc/front/op17/10130.jpg",
    "color": "Yellow",
    "colorDot": "#facc15",
    "rank": "#1 Tier 1",
    "winrate": "65.2%",
    "date": "28/08/2026",
    "tournament": "OnePieceTopDecks Flagship Battle Champion",
    "source": "OnePieceTopDecks",
    "metaEra": "OP-17",
    "tier": "Tier 1",
    "description": "High-tier Yellow Big Mom Pirates control engine utilizing Streusen triggers, Oven board removal, and Katakuri life-manipulation.",
    "cards": [
      {
        "cardId": "OP17-113",
        "name": "Streusen",
        "quantity": 4,
        "cost": 1,
        "power": 2000,
        "category": "Character",
        "colors": "Yellow",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op17/10148.jpg",
        "yuyuPrice": 120,
        "marketPrice": 0.86
      },
      {
        "cardId": "OP17-104",
        "name": "Charlotte Cracker",
        "quantity": 4,
        "cost": 3,
        "power": 4000,
        "category": "Character",
        "colors": "Yellow",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op17/10136.jpg",
        "yuyuPrice": 80,
        "marketPrice": 0.57
      },
      {
        "cardId": "OP17-107",
        "name": "Charlotte Daifuku",
        "quantity": 4,
        "cost": 3,
        "power": 4000,
        "category": "Character",
        "colors": "Yellow",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op17/10139.jpg",
        "yuyuPrice": 120,
        "marketPrice": 0.86
      },
      {
        "cardId": "OP17-109",
        "name": "Charlotte Pudding",
        "quantity": 4,
        "cost": 3,
        "power": 4000,
        "category": "Character",
        "colors": "Yellow",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op17/10142.jpg",
        "yuyuPrice": 320,
        "marketPrice": 2.29
      },
      {
        "cardId": "OP17-108",
        "name": "Charlotte Brulee",
        "quantity": 4,
        "cost": 3,
        "power": 4000,
        "category": "Character",
        "colors": "Yellow",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op17/10141.jpg",
        "yuyuPrice": 50,
        "marketPrice": 0.36
      },
      {
        "cardId": "OP17-112",
        "name": "Charlotte Linlin",
        "quantity": 4,
        "cost": 10,
        "power": 12000,
        "category": "Character",
        "colors": "Yellow",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op17/10145.jpg",
        "yuyuPrice": 420,
        "marketPrice": 3
      },
      {
        "cardId": "OP17-106",
        "name": "Charlotte Smoothie",
        "quantity": 4,
        "cost": 5,
        "power": 4000,
        "category": "Character",
        "colors": "Yellow",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op17/10138.jpg",
        "yuyuPrice": 80,
        "marketPrice": 0.57
      },
      {
        "cardId": "OP17-105",
        "name": "Charlotte Chiffon",
        "quantity": 4,
        "cost": 5,
        "power": null,
        "category": "Character",
        "colors": "Yellow",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op17/10137.jpg",
        "yuyuPrice": 50,
        "marketPrice": 0.36
      },
      {
        "cardId": "OP17-101",
        "name": "Caribou",
        "quantity": 4,
        "cost": 5,
        "power": 6000,
        "category": "Character",
        "colors": "Yellow",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op17/10133.jpg",
        "yuyuPrice": 50,
        "marketPrice": 0.36
      },
      {
        "cardId": "OP17-100",
        "name": "Capone\"Gang\"Bege",
        "quantity": 4,
        "cost": 7,
        "power": 8000,
        "category": "Character",
        "colors": "Yellow",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op17/10132.jpg",
        "yuyuPrice": 50,
        "marketPrice": 0.36
      },
      {
        "cardId": "OP17-110",
        "name": "Charlotte Perospero",
        "quantity": 4,
        "cost": 7,
        "power": 4000,
        "category": "Character",
        "colors": "Yellow",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op17/10143.jpg",
        "yuyuPrice": 50,
        "marketPrice": 0.36
      },
      {
        "cardId": "OP17-114",
        "name": "Sweet 3 Generals",
        "quantity": 4,
        "cost": 6,
        "power": 4000,
        "category": "Character",
        "colors": "Yellow",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op17/10149.jpg",
        "yuyuPrice": 120,
        "marketPrice": 0.86
      },
      {
        "cardId": "OP17-115",
        "name": "Don't you know that even in the cruel world of pirates there's still a code of honor?!!",
        "quantity": 2,
        "cost": 1,
        "power": null,
        "category": "Event",
        "colors": "Yellow",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op17/10151.jpg",
        "yuyuPrice": 120,
        "marketPrice": 0.86
      }
    ],
    "stats": {
      "charactersCount": 48,
      "eventsCount": 2,
      "stagesCount": 0,
      "counters2000": 12,
      "counters1000": 32,
      "noCounter": 6,
      "avgCost": 4.7
    }
  },
  {
    "id": "black-monkey-d-luffy-op17",
    "name": "(Black) Monkey.D.Luffy",
    "subname": "Egghead Gear 5 Combo",
    "leaderId": "OP17-079",
    "leaderName": "Monkey.D.Luffy",
    "leaderImage": "https://card.yuyu-tei.jp/opc/front/op17/10103.jpg",
    "color": "Black",
    "colorDot": "#6b7280",
    "rank": "#1 Tier 1",
    "winrate": "63.9%",
    "date": "28/08/2026",
    "tournament": "OnePieceTopDecks Masters Cup Finalist",
    "source": "OnePieceTopDecks",
    "metaEra": "OP-17",
    "tier": "Tier 1",
    "description": "Relentless cost-reduction beatdown utilizing Egghead research units and Gear 5 finisher to remove high-cost threats while preserving card economy.",
    "cards": [
      {
        "cardId": "OP17-080",
        "name": "Usopp",
        "quantity": 4,
        "cost": 2,
        "power": 2000,
        "category": "Character",
        "colors": "Black",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op17/10107.jpg",
        "yuyuPrice": 220,
        "marketPrice": 1.57
      },
      {
        "cardId": "OP17-081",
        "name": "Gerd",
        "quantity": 4,
        "cost": 2,
        "power": 3000,
        "category": "Character",
        "colors": "Black",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op17/10109.jpg",
        "yuyuPrice": 120,
        "marketPrice": 0.86
      },
      {
        "cardId": "OP17-082",
        "name": "Sanji",
        "quantity": 4,
        "cost": 2,
        "power": 2000,
        "category": "Character",
        "colors": "Black",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op17/10110.jpg",
        "yuyuPrice": 50,
        "marketPrice": 0.36
      },
      {
        "cardId": "OP17-083",
        "name": "Jinbe",
        "quantity": 4,
        "cost": 2,
        "power": 2000,
        "category": "Character",
        "colors": "Black",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op17/10111.jpg",
        "yuyuPrice": 50,
        "marketPrice": 0.36
      },
      {
        "cardId": "OP17-084",
        "name": "Tony Tony.Chopper",
        "quantity": 4,
        "cost": 1,
        "power": 2000,
        "category": "Character",
        "colors": "Black",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op17/10112.jpg",
        "yuyuPrice": 80,
        "marketPrice": 0.57
      },
      {
        "cardId": "OP17-085",
        "name": "Dorry",
        "quantity": 4,
        "cost": 5,
        "power": 5000,
        "category": "Character",
        "colors": "Black",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op17/10113.jpg",
        "yuyuPrice": 80,
        "marketPrice": 0.57
      },
      {
        "cardId": "OP17-086",
        "name": "Nami",
        "quantity": 4,
        "cost": 1,
        "power": 2000,
        "category": "Character",
        "colors": "Black",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op17/10114.jpg",
        "yuyuPrice": 120,
        "marketPrice": 0.86
      },
      {
        "cardId": "OP17-087",
        "name": "Nico Robin",
        "quantity": 4,
        "cost": 2,
        "power": 2000,
        "category": "Character",
        "colors": "Black",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op17/10115.jpg",
        "yuyuPrice": 120,
        "marketPrice": 0.86
      },
      {
        "cardId": "OP17-088",
        "name": "Hajrudin",
        "quantity": 4,
        "cost": 7,
        "power": 8000,
        "category": "Character",
        "colors": "Black",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op17/10117.jpg",
        "yuyuPrice": 50,
        "marketPrice": 0.36
      },
      {
        "cardId": "OP17-089",
        "name": "Jaguar.D.Saul",
        "quantity": 4,
        "cost": 4,
        "power": 6000,
        "category": "Character",
        "colors": "Black",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op17/10119.jpg",
        "yuyuPrice": 220,
        "marketPrice": 1.57
      },
      {
        "cardId": "OP17-090",
        "name": "Franky",
        "quantity": 4,
        "cost": 2,
        "power": 2000,
        "category": "Character",
        "colors": "Black",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op17/10120.jpg",
        "yuyuPrice": 50,
        "marketPrice": 0.36
      },
      {
        "cardId": "OP17-091",
        "name": "Brook",
        "quantity": 4,
        "cost": 2,
        "power": 2000,
        "category": "Character",
        "colors": "Black",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op17/10121.jpg",
        "yuyuPrice": 50,
        "marketPrice": 0.36
      },
      {
        "cardId": "OP17-092",
        "name": "Brogy",
        "quantity": 2,
        "cost": 5,
        "power": 5000,
        "category": "Character",
        "colors": "Black",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op17/10122.jpg",
        "yuyuPrice": 80,
        "marketPrice": 0.57
      }
    ],
    "stats": {
      "charactersCount": 50,
      "eventsCount": 0,
      "stagesCount": 0,
      "counters2000": 12,
      "counters1000": 34,
      "noCounter": 4,
      "avgCost": 2.8
    }
  },
  {
    "id": "purple-kaido-op17",
    "name": "(Purple) Kaido",
    "subname": "Beast Pirates Thunder Bagua",
    "leaderId": "OP17-058",
    "leaderName": "Kaido",
    "leaderImage": "https://card.yuyu-tei.jp/opc/front/op17/10076.jpg",
    "color": "Purple",
    "colorDot": "#a855f7",
    "rank": "#2 Tier 1",
    "winrate": "61.4%",
    "date": "27/08/2026",
    "tournament": "OnePieceTopDecks Standard Battle 1st Place",
    "source": "OnePieceTopDecks",
    "metaEra": "OP-17",
    "tier": "Tier 1",
    "description": "High-octane ramp deck speeding into 10-cost Kaido, King, and Queen board wipes through dynamic DON!! recovery effects.",
    "cards": [
      {
        "cardId": "OP17-059",
        "name": "Aramaki",
        "quantity": 4,
        "cost": 7,
        "power": 8000,
        "category": "Character",
        "colors": "Purple",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op17/10078.jpg",
        "yuyuPrice": 80,
        "marketPrice": 0.57
      },
      {
        "cardId": "OP17-060",
        "name": "Ulti & Page One",
        "quantity": 4,
        "cost": 6,
        "power": 6000,
        "category": "Character",
        "colors": "Purple",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op17/10079.jpg",
        "yuyuPrice": 120,
        "marketPrice": 0.86
      },
      {
        "cardId": "OP17-061",
        "name": "Lead Performers",
        "quantity": 4,
        "cost": 9,
        "power": 11000,
        "category": "Character",
        "colors": "Purple",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op17/10080.jpg",
        "yuyuPrice": 120,
        "marketPrice": 0.86
      },
      {
        "cardId": "OP17-062",
        "name": "Kaido",
        "quantity": 4,
        "cost": 10,
        "power": 12000,
        "category": "Character",
        "colors": "Purple",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op17/10082.jpg",
        "yuyuPrice": 220,
        "marketPrice": 1.57
      },
      {
        "cardId": "OP17-063",
        "name": "Kaido",
        "quantity": 4,
        "cost": 10,
        "power": 12000,
        "category": "Character",
        "colors": "Purple",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op17/10086.jpg",
        "yuyuPrice": 220,
        "marketPrice": 1.57
      },
      {
        "cardId": "OP17-064",
        "name": "King",
        "quantity": 4,
        "cost": 9,
        "power": 10000,
        "category": "Character",
        "colors": "Purple",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op17/10088.jpg",
        "yuyuPrice": 50,
        "marketPrice": 0.36
      },
      {
        "cardId": "OP17-065",
        "name": "Queen",
        "quantity": 4,
        "cost": 9,
        "power": 10000,
        "category": "Character",
        "colors": "Purple",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op17/10089.jpg",
        "yuyuPrice": 80,
        "marketPrice": 0.57
      },
      {
        "cardId": "OP17-066",
        "name": "Kurozumi Orochi",
        "quantity": 4,
        "cost": 1,
        "power": null,
        "category": "Character",
        "colors": "Purple",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op17/10090.jpg",
        "yuyuPrice": 50,
        "marketPrice": 0.36
      },
      {
        "cardId": "OP17-067",
        "name": "Kurozumi Kanjuro",
        "quantity": 4,
        "cost": 2,
        "power": 3000,
        "category": "Character",
        "colors": "Purple",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op17/10091.jpg",
        "yuyuPrice": 50,
        "marketPrice": 0.36
      },
      {
        "cardId": "OP17-068",
        "name": "Sasaki",
        "quantity": 4,
        "cost": 3,
        "power": 4000,
        "category": "Character",
        "colors": "Purple",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op17/10092.jpg",
        "yuyuPrice": 50,
        "marketPrice": 0.36
      },
      {
        "cardId": "OP17-069",
        "name": "Jack",
        "quantity": 4,
        "cost": 9,
        "power": 10000,
        "category": "Character",
        "colors": "Purple",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op17/10093.jpg",
        "yuyuPrice": 80,
        "marketPrice": 0.57
      },
      {
        "cardId": "OP17-070",
        "name": "Scratchmen Apoo",
        "quantity": 4,
        "cost": 6,
        "power": 7000,
        "category": "Character",
        "colors": "Purple",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op17/10094.jpg",
        "yuyuPrice": 50,
        "marketPrice": 0.36
      },
      {
        "cardId": "OP17-071",
        "name": "Who's.Who",
        "quantity": 2,
        "cost": 2,
        "power": 3000,
        "category": "Character",
        "colors": "Purple",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op17/10096.jpg",
        "yuyuPrice": 50,
        "marketPrice": 0.36
      }
    ],
    "stats": {
      "charactersCount": 50,
      "eventsCount": 0,
      "stagesCount": 0,
      "counters2000": 8,
      "counters1000": 14,
      "noCounter": 28,
      "avgCost": 6.6
    }
  },
  {
    "id": "blue-rocks-d-xebec-op17",
    "name": "(Blue) Rocks.D.Xebec",
    "subname": "God Valley Legend",
    "leaderId": "OP17-039",
    "leaderName": "Rocks.D.Xebec",
    "leaderImage": "https://card.yuyu-tei.jp/opc/front/op17/10050.jpg",
    "color": "Blue",
    "colorDot": "#3b82f6",
    "rank": "#2 Tier 1",
    "winrate": "62.1%",
    "date": "27/08/2026",
    "tournament": "OnePieceTopDecks Grand Prix Top 4",
    "source": "OnePieceTopDecks",
    "metaEra": "OP-17",
    "tier": "Tier 1",
    "description": "Devastating bounce control deck sending opponent cards back to hand or deck bottom, starving opposing leaders of tempo and board presence.",
    "cards": [
      {
        "cardId": "OP17-040",
        "name": "Edward.Newgate",
        "quantity": 4,
        "cost": 6,
        "power": 8000,
        "category": "Character",
        "colors": "Blue",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op17/10053.jpg",
        "yuyuPrice": 120,
        "marketPrice": 0.86
      },
      {
        "cardId": "OP17-041",
        "name": "Wang Zhi",
        "quantity": 4,
        "cost": 4,
        "power": 6000,
        "category": "Character",
        "colors": "Blue",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op17/10054.jpg",
        "yuyuPrice": 80,
        "marketPrice": 0.57
      },
      {
        "cardId": "OP17-042",
        "name": "Kaido",
        "quantity": 4,
        "cost": 4,
        "power": 6000,
        "category": "Character",
        "colors": "Blue",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op17/10055.jpg",
        "yuyuPrice": 120,
        "marketPrice": 0.86
      },
      {
        "cardId": "OP17-043",
        "name": "Ganzui",
        "quantity": 4,
        "cost": 5,
        "power": 7000,
        "category": "Character",
        "colors": "Blue",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op17/10056.jpg",
        "yuyuPrice": 80,
        "marketPrice": 0.57
      },
      {
        "cardId": "OP17-044",
        "name": "Captain John",
        "quantity": 4,
        "cost": 4,
        "power": 6000,
        "category": "Character",
        "colors": "Blue",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op17/10057.jpg",
        "yuyuPrice": 80,
        "marketPrice": 0.57
      },
      {
        "cardId": "OP17-045",
        "name": "Kyo",
        "quantity": 4,
        "cost": 2,
        "power": 4000,
        "category": "Character",
        "colors": "Blue",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op17/10058.jpg",
        "yuyuPrice": 80,
        "marketPrice": 0.57
      },
      {
        "cardId": "OP17-046",
        "name": "Gloriosa",
        "quantity": 4,
        "cost": 4,
        "power": 1000,
        "category": "Character",
        "colors": "Blue",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op17/10060.jpg",
        "yuyuPrice": 220,
        "marketPrice": 1.57
      },
      {
        "cardId": "OP17-047",
        "name": "Shiki",
        "quantity": 4,
        "cost": 9,
        "power": 10000,
        "category": "Character",
        "colors": "Blue",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op17/10062.jpg",
        "yuyuPrice": 50,
        "marketPrice": 0.36
      },
      {
        "cardId": "OP17-048",
        "name": "Shiki",
        "quantity": 4,
        "cost": 7,
        "power": 9000,
        "category": "Character",
        "colors": "Blue",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op17/10063.jpg",
        "yuyuPrice": 220,
        "marketPrice": 1.57
      },
      {
        "cardId": "OP17-049",
        "name": "Charlotte Linlin",
        "quantity": 4,
        "cost": 5,
        "power": 7000,
        "category": "Character",
        "colors": "Blue",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op17/10065.jpg",
        "yuyuPrice": 120,
        "marketPrice": 0.86
      },
      {
        "cardId": "OP17-050",
        "name": "Streusen",
        "quantity": 4,
        "cost": 1,
        "power": 2000,
        "category": "Character",
        "colors": "Blue",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op17/10067.jpg",
        "yuyuPrice": 50,
        "marketPrice": 0.36
      },
      {
        "cardId": "OP17-051",
        "name": "Jinbe",
        "quantity": 4,
        "cost": 7,
        "power": 8000,
        "category": "Character",
        "colors": "Blue",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op17/10068.jpg",
        "yuyuPrice": 50,
        "marketPrice": 0.36
      },
      {
        "cardId": "OP17-052",
        "name": "Don Marlon",
        "quantity": 2,
        "cost": 3,
        "power": 5000,
        "category": "Character",
        "colors": "Blue",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op17/10069.jpg",
        "yuyuPrice": 50,
        "marketPrice": 0.36
      }
    ],
    "stats": {
      "charactersCount": 50,
      "eventsCount": 0,
      "stagesCount": 0,
      "counters2000": 4,
      "counters1000": 0,
      "noCounter": 46,
      "avgCost": 4.8
    }
  },
  {
    "id": "green-shanks-op17",
    "name": "(Green) Shanks",
    "subname": "Red Hair Pirates Film Slash",
    "leaderId": "OP17-020",
    "leaderName": "Shanks",
    "leaderImage": "https://card.yuyu-tei.jp/opc/front/op17/10025.jpg",
    "color": "Green",
    "colorDot": "#22c55e",
    "rank": "#3 Tier 1.5",
    "winrate": "59.7%",
    "date": "26/08/2026",
    "tournament": "OnePieceTopDecks Regional Cup Winner",
    "source": "OnePieceTopDecks",
    "metaEra": "OP-17",
    "tier": "Tier 1.5",
    "description": "Agile rest-standing tempo archetype. Restands powerhouse attackers and bypasses blockers with high-efficiency Film synergy.",
    "cards": [
      {
        "cardId": "OP17-021",
        "name": "Crone Oli",
        "quantity": 4,
        "cost": 1,
        "power": null,
        "category": "Character",
        "colors": "Green",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op17/10026.jpg",
        "yuyuPrice": 80,
        "marketPrice": 0.57
      },
      {
        "cardId": "OP17-022",
        "name": "Shanks",
        "quantity": 4,
        "cost": 10,
        "power": 12000,
        "category": "Character",
        "colors": "Green",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op17/10027.jpg",
        "yuyuPrice": 580,
        "marketPrice": 4.14
      },
      {
        "cardId": "OP17-023",
        "name": "Nami",
        "quantity": 4,
        "cost": 1,
        "power": 1000,
        "category": "Character",
        "colors": "Green",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op17/10030.jpg",
        "yuyuPrice": 80,
        "marketPrice": 0.57
      },
      {
        "cardId": "OP17-024",
        "name": "Howling Gab",
        "quantity": 4,
        "cost": 8,
        "power": 8000,
        "category": "Character",
        "colors": "Green",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op17/10031.jpg",
        "yuyuPrice": 50,
        "marketPrice": 0.36
      },
      {
        "cardId": "OP17-025",
        "name": "Building Snake",
        "quantity": 4,
        "cost": 4,
        "power": 5000,
        "category": "Character",
        "colors": "Green",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op17/10032.jpg",
        "yuyuPrice": 80,
        "marketPrice": 0.57
      },
      {
        "cardId": "OP17-026",
        "name": "Fugar",
        "quantity": 4,
        "cost": 1,
        "power": 2000,
        "category": "Character",
        "colors": "Green",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op17/10034.jpg",
        "yuyuPrice": 80,
        "marketPrice": 0.57
      },
      {
        "cardId": "OP17-027",
        "name": "Benn.Beckman",
        "quantity": 4,
        "cost": 7,
        "power": 9000,
        "category": "Character",
        "colors": "Green",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op17/10035.jpg",
        "yuyuPrice": 120,
        "marketPrice": 0.86
      },
      {
        "cardId": "OP17-028",
        "name": "Bonk Punch & Monster",
        "quantity": 4,
        "cost": 4,
        "power": 3000,
        "category": "Character",
        "colors": "Green",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op17/10037.jpg",
        "yuyuPrice": 50,
        "marketPrice": 0.36
      },
      {
        "cardId": "OP17-029",
        "name": "Hongo",
        "quantity": 4,
        "cost": 4,
        "power": 4000,
        "category": "Character",
        "colors": "Green",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op17/10038.jpg",
        "yuyuPrice": 120,
        "marketPrice": 0.86
      },
      {
        "cardId": "OP17-030",
        "name": "Monkey.D.Luffy",
        "quantity": 4,
        "cost": 4,
        "power": 5000,
        "category": "Character",
        "colors": "Green",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op17/10039.jpg",
        "yuyuPrice": 50,
        "marketPrice": 0.36
      },
      {
        "cardId": "OP17-031",
        "name": "Yasopp",
        "quantity": 4,
        "cost": 5,
        "power": 6000,
        "category": "Character",
        "colors": "Green",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op17/10040.jpg",
        "yuyuPrice": 320,
        "marketPrice": 2.29
      },
      {
        "cardId": "OP17-032",
        "name": "Limejuice",
        "quantity": 4,
        "cost": 1,
        "power": 2000,
        "category": "Character",
        "colors": "Green",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op17/10042.jpg",
        "yuyuPrice": 120,
        "marketPrice": 0.86
      },
      {
        "cardId": "OP17-033",
        "name": "Lucky.Roux",
        "quantity": 2,
        "cost": 4,
        "power": 5000,
        "category": "Character",
        "colors": "Green",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op17/10043.jpg",
        "yuyuPrice": 120,
        "marketPrice": 0.86
      }
    ],
    "stats": {
      "charactersCount": 50,
      "eventsCount": 0,
      "stagesCount": 0,
      "counters2000": 20,
      "counters1000": 22,
      "noCounter": 8,
      "avgCost": 4.2
    }
  },
  {
    "id": "red-edward-newgate-op17",
    "name": "(Red) Edward.Newgate",
    "subname": "Whitebeard Pirates Tremor Power",
    "leaderId": "OP17-001",
    "leaderName": "Edward.Newgate",
    "leaderImage": "https://card.yuyu-tei.jp/opc/front/op17/10001.jpg",
    "color": "Red",
    "colorDot": "#ef4444",
    "rank": "#3 Tier 1.5",
    "winrate": "59.1%",
    "date": "26/08/2026",
    "tournament": "OnePieceTopDecks Challenge Cup Champion",
    "source": "OnePieceTopDecks",
    "metaEra": "OP-17",
    "tier": "Tier 1.5",
    "description": "Heavyweight attack leader fielding 6000 base power and huge statlines that force opponents into difficult defensive calculations.",
    "cards": [
      {
        "cardId": "OP17-002",
        "name": "Atmos",
        "quantity": 4,
        "cost": 4,
        "power": 6000,
        "category": "Character",
        "colors": "Red",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op17/10003.jpg",
        "yuyuPrice": 50,
        "marketPrice": 0.36
      },
      {
        "cardId": "OP17-003",
        "name": "Izo",
        "quantity": 4,
        "cost": 4,
        "power": 6000,
        "category": "Character",
        "colors": "Red",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op17/10004.jpg",
        "yuyuPrice": 120,
        "marketPrice": 0.86
      },
      {
        "cardId": "OP17-004",
        "name": "Inuarashi & Nekomamushi",
        "quantity": 4,
        "cost": 3,
        "power": 2000,
        "category": "Character",
        "colors": "Red",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op17/10005.jpg",
        "yuyuPrice": 50,
        "marketPrice": 0.36
      },
      {
        "cardId": "OP17-005",
        "name": "Edward.Newgate",
        "quantity": 4,
        "cost": 10,
        "power": 12000,
        "category": "Character",
        "colors": "Red",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op17/10006.jpg",
        "yuyuPrice": 220,
        "marketPrice": 1.57
      },
      {
        "cardId": "OP17-006",
        "name": "Kingdew",
        "quantity": 4,
        "cost": 7,
        "power": 8000,
        "category": "Character",
        "colors": "Red",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op17/10009.jpg",
        "yuyuPrice": 50,
        "marketPrice": 0.36
      },
      {
        "cardId": "OP17-007",
        "name": "Kouzuki Oden",
        "quantity": 4,
        "cost": 7,
        "power": 8000,
        "category": "Character",
        "colors": "Red",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op17/10011.jpg",
        "yuyuPrice": 120,
        "marketPrice": 0.86
      },
      {
        "cardId": "OP17-008",
        "name": "Jozu",
        "quantity": 4,
        "cost": 6,
        "power": 8000,
        "category": "Character",
        "colors": "Red",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op17/10012.jpg",
        "yuyuPrice": 120,
        "marketPrice": 0.86
      },
      {
        "cardId": "OP17-009",
        "name": "Haruta",
        "quantity": 4,
        "cost": 4,
        "power": 5000,
        "category": "Character",
        "colors": "Red",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op17/10013.jpg",
        "yuyuPrice": 80,
        "marketPrice": 0.57
      },
      {
        "cardId": "OP17-010",
        "name": "Fossa",
        "quantity": 4,
        "cost": 1,
        "power": 3000,
        "category": "Character",
        "colors": "Red",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op17/10014.jpg",
        "yuyuPrice": 50,
        "marketPrice": 0.36
      },
      {
        "cardId": "OP17-011",
        "name": "Blamenco",
        "quantity": 4,
        "cost": 5,
        "power": 6000,
        "category": "Character",
        "colors": "Red",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op17/10015.jpg",
        "yuyuPrice": 50,
        "marketPrice": 0.36
      },
      {
        "cardId": "OP17-012",
        "name": "Blenheim",
        "quantity": 4,
        "cost": 2,
        "power": 1000,
        "category": "Character",
        "colors": "Red",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op17/10016.jpg",
        "yuyuPrice": 50,
        "marketPrice": 0.36
      },
      {
        "cardId": "OP17-013",
        "name": "Portgas.D.Ace",
        "quantity": 4,
        "cost": 6,
        "power": 6000,
        "category": "Character",
        "colors": "Red",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op17/10017.jpg",
        "yuyuPrice": 80,
        "marketPrice": 0.57
      },
      {
        "cardId": "OP17-014",
        "name": "Whitey Bay",
        "quantity": 2,
        "cost": 1,
        "power": 1000,
        "category": "Character",
        "colors": "Red",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op17/10018.jpg",
        "yuyuPrice": 50,
        "marketPrice": 0.36
      }
    ],
    "stats": {
      "charactersCount": 50,
      "eventsCount": 0,
      "stagesCount": 0,
      "counters2000": 8,
      "counters1000": 18,
      "noCounter": 24,
      "avgCost": 4.8
    }
  },
  {
    "id": "yellow-charlotte-katakuri-op03",
    "name": "(Yellow) Charlotte Katakuri",
    "subname": "Big Mom Pirates 7000 Powerhouse",
    "leaderId": "OP03-099",
    "leaderName": "Charlotte Katakuri",
    "leaderImage": "https://card.yuyu-tei.jp/opc/front/st20/10006.jpg",
    "color": "Yellow",
    "colorDot": "#eab308",
    "rank": "#3 Tier 1.5",
    "winrate": "57.8%",
    "date": "29/08/2026",
    "tournament": "OnePieceTopDecks Regional Cup Top 4",
    "source": "OnePieceTopDecks",
    "metaEra": "OP-08",
    "tier": "Tier 1.5",
    "description": "Relentless 7000-power offensive leader. Rearranges life cards with Katakuri ability to trigger game-saving Amaru, Cracker, and Thunder Bolt effects.",
    "cards": [
      {
        "cardId": "OP03-123",
        "name": "Charlotte Katakuri",
        "quantity": 4,
        "cost": 8,
        "power": 8000,
        "category": "Character",
        "colors": "Yellow",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/prb01/10076.jpg",
        "yuyuPrice": 220,
        "marketPrice": 1.57
      },
      {
        "cardId": "OP03-114",
        "name": "Charlotte Linlin",
        "quantity": 4,
        "cost": 10,
        "power": 12000,
        "category": "Character",
        "colors": "Yellow",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op03/10137.jpg",
        "yuyuPrice": 220,
        "marketPrice": 1.57
      },
      {
        "cardId": "OP03-112",
        "name": "Charlotte Pudding",
        "quantity": 4,
        "cost": 1,
        "power": 2000,
        "category": "Character",
        "colors": "Yellow",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/st20/10008.jpg",
        "yuyuPrice": 50,
        "marketPrice": 0.36
      },
      {
        "cardId": "OP03-113",
        "name": "Charlotte Perospero",
        "quantity": 4,
        "cost": 3,
        "power": 5000,
        "category": "Character",
        "colors": "Yellow",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op03/10135.jpg",
        "yuyuPrice": 80,
        "marketPrice": 0.57
      },
      {
        "cardId": "OP03-115",
        "name": "Streusen",
        "quantity": 4,
        "cost": 1,
        "power": 1000,
        "category": "Character",
        "colors": "Yellow",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/st20/10009.jpg",
        "yuyuPrice": 50,
        "marketPrice": 0.36
      },
      {
        "cardId": "OP03-108",
        "name": "Charlotte Cracker",
        "quantity": 4,
        "cost": 4,
        "power": 5000,
        "category": "Character",
        "colors": "Yellow",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op03/10128.jpg",
        "yuyuPrice": 80,
        "marketPrice": 0.57
      },
      {
        "cardId": "OP03-102",
        "name": "Sanji",
        "quantity": 4,
        "cost": 2,
        "power": 3000,
        "category": "Character",
        "colors": "Yellow",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op03/10122.jpg",
        "yuyuPrice": 80,
        "marketPrice": 0.57
      },
      {
        "cardId": "OP04-100",
        "name": "Capone\"Gang\"Bege",
        "quantity": 4,
        "cost": 3,
        "power": 3000,
        "category": "Character",
        "colors": "Yellow",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/prb01/10095.jpg",
        "yuyuPrice": 120,
        "marketPrice": 0.86
      },
      {
        "cardId": "OP04-104",
        "name": "Sanji",
        "quantity": 4,
        "cost": 4,
        "power": 5000,
        "category": "Character",
        "colors": "Yellow",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op04/10125.jpg",
        "yuyuPrice": 80,
        "marketPrice": 0.57
      },
      {
        "cardId": "OP04-112",
        "name": "Yamato",
        "quantity": 4,
        "cost": 9,
        "power": 9000,
        "category": "Character",
        "colors": "Yellow",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op04/10134.jpg",
        "yuyuPrice": 120,
        "marketPrice": 0.86
      },
      {
        "cardId": "OP03-121",
        "name": "Thunder Bolt",
        "quantity": 4,
        "cost": 2,
        "power": null,
        "category": "Event",
        "colors": "Yellow",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op03/10145.jpg",
        "yuyuPrice": 30,
        "marketPrice": 0.21
      },
      {
        "cardId": "OP03-122",
        "name": "Sogeking",
        "quantity": 4,
        "cost": 7,
        "power": 6000,
        "category": "Character",
        "colors": "Blue",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op03/10146.jpg",
        "yuyuPrice": 580,
        "marketPrice": 4.14
      },
      {
        "cardId": "OP05-115",
        "name": "Two-Hundred Million Volts Amaru",
        "quantity": 2,
        "cost": 2,
        "power": null,
        "category": "Event",
        "colors": "Yellow",
        "imageUrl": "https://card.yuyu-tei.jp/opc/front/op05/10139.jpg",
        "yuyuPrice": 80,
        "marketPrice": 0.57
      }
    ],
    "stats": {
      "charactersCount": 44,
      "eventsCount": 6,
      "stagesCount": 0,
      "counters2000": 12,
      "counters1000": 16,
      "noCounter": 22,
      "avgCost": 4.4
    }
  }
];

export function getDeckById(id: string): RecommendedDeck | undefined {
  return RECOMMENDED_DECKS.find((d) => d.id === id || d.leaderId.toLowerCase() === id.toLowerCase());
}

export function formatDeckExport(deck: RecommendedDeck): string {
  const lines: string[] = [];
  lines.push(`// Leader: ${deck.leaderName} (${deck.leaderId})`);
  lines.push(`1x${deck.leaderId}`);
  for (const c of deck.cards) {
    lines.push(`${c.quantity}x${c.cardId}`);
  }
  return lines.join('\n');
}
